name: CI Pipeline for Selenium + Cucumber

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: false
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Set up Chrome and ChromeDriver (replacing custom install)
      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: 'stable'
          install-chromedriver: true
          install-dependencies: true

      # Run tests (Maven + Cucumber)
      - name: Run Cucumber Tests
        run: mvn clean verify  # Use verify to include reporting
        env:
          HEADLESS: true
          ENVIRONMENT: ${{ github.event.inputs.environment || 'staging' }}

      # Upload reports as artifacts
      - name: Upload Test Reports
        if: always()  # Upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: target/cucumber-reports/  # Ensure this matches your output